# Generated by Django 3.2.11 on 2022-01-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakersocialmedia',
            name='speaker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.speaker'),
        ),
    ]
