# Generated by Django 3.2.11 on 2022-01-20 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_keynote_keynotespeaker_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='keynote',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.stage'),
            preserve_default=False,
        ),
    ]
