# Generated by Django 3.2.11 on 2022-01-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220120_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keynote',
            old_name='state',
            new_name='stage',
        ),
    ]
